name: Server CI Pipeline

on:
    push: 
        branches: [main, develop]
    pull_request: 
        branches: [main, develop]

env:
    PRISMA_HIDE_UPDATE_MESSAGE: "1"

jobs:
    build-test:
        strategy:
            matrix:
                os: [ubuntu-latest]
        
        runs-on: ${{matrix.os}}

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Install pnpm
              uses: pnpm/action-setup@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                node-version: 24
                cache: 'pnpm'

            - name: Install dependencies
              run: pnpm install --frozen-lockfile

            - name: Generate Prisma Client
              run: cd backend && pnpm prisma:generate

            - name: Run Lint
              run: pnpm run lint

            - name: Type Check
              run: pnpm run type-check

            - name: Run Tests
              run: pnpm run test:ci

            - name: Build project
              run: pnpm run build

            - name: Setup Rust
              uses: dtolnay/rust-toolchain@stable
              with:
                toolchain: stable

            - name: Build Contracts
              run: |
                cargo build --release --manifest-path ./contracts/credit-score/Cargo.toml
                cargo build --release --manifest-path ./contracts/fraud-detect/Cargo.toml

            - name: Test Contracts
              run: |
                cargo test --manifest-path ./contracts/credit-score/Cargo.toml
                cargo test --manifest-path ./contracts/fraud-detect/Cargo.toml

            - name: Upload Contract Artifacts
              uses: actions/upload-artifact@v4
              with:
                name: contracts-build
                path: |
                    contracts/**/target/release/*.rlib
                    contracts/**/target/wasm32-unknown-unknown/release/*.wasm